### ISSUE TITLE
Modelo de Negocios

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-team-desarrollosoftware#1]
[ModeloNegocios-LuzArleth-SaullLB.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-team-desarrollosoftware/files/12821236/ModeloNegocios-LuzArleth-SaullLB.pdf)

**Comment by Sandoval6** [comment]
calificacion=19.4

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
