### ISSUE TITLE
practica 1 modelo de negocio Heladeria

### ISSUE THREAD

**Issue by Sandoval6** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-team-desarrollosoftware#2]
[reporte 1 .pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-team-desarrollosoftware/files/12825681/reporte.1.pdf)

**Comment by isaireyesp1** [comment]
Portada : 22
Procedimiento : 22
Figuras, ilustraciones y fotografías. : 17
Resultados y conclusiones  :  15
calificación : 15.2

observaciones :  hace falta mas imágenes y los resultados, aparte su conclusión es de solo 6 renglones

**Comment by Luz1727** [comment]
Portada= 25 puntos.
Procedimiento = 23 puntos.
Figuras y Descripción de figuras=17 puntos.
Conclusión = 17 puntos.
Calificación = 16.4%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
